# Dockerfile
FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY list_labels.py .
COPY template.html .

CMD ["python", "list_labels.py"]
    